# Generated by Django 5.2.6 on 2025-10-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibilita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sedia_a_rotelle', models.BooleanField(default=False)),
                ('ausili_visivi', models.BooleanField(default=False)),
                ('supporto_audioguide', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descrizione', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('regione', models.CharField(max_length=100)),
                ('citta', models.CharField(blank=True, max_length=100)),
                ('latitudine', models.FloatField(blank=True, null=True)),
                ('longitudine', models.FloatField(blank=True, null=True)),
                ('anno_iscrizione', models.IntegerField(blank=True, null=True)),
                ('unesco_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('accessibilita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heritage.accessibilita')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heritage.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tappa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveIntegerField()),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritage.itinerario')),
                ('sito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritage.sito')),
            ],
            options={
                'ordering': ['ordine'],
            },
        ),
    ]
