# Generated by Django 5.2.6 on 2025-10-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessibilita',
            old_name='supporto_audioguide',
            new_name='supporto_uditivo',
        ),
    ]
