# Generated by Django 5.2.6 on 2025-10-09 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0002_rename_supporto_audioguide_accessibilita_supporto_uditivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sito',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heritage.categoria'),
        ),
        migrations.AlterField(
            model_name='sito',
            name='regione',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sito',
            name='unesco_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tappa',
            name='itinerario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tappe', to='heritage.itinerario'),
        ),
        migrations.AlterField(
            model_name='tappa',
            name='ordine',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
