# Generated by Django 5.2.6 on 2025-10-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0003_alter_sito_categoria_alter_sito_regione_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tappa',
            constraint=models.UniqueConstraint(fields=('itinerario', 'ordine'), name='tappa_unique_itin_ordine'),
        ),
    ]
