# Generated by Django 5.2.6 on 2025-10-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0004_tappa_tappa_unique_itin_ordine'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sito',
            index=models.Index(fields=['regione'], name='heritage_si_regione_cf873f_idx'),
        ),
        migrations.AddIndex(
            model_name='sito',
            index=models.Index(fields=['citta'], name='heritage_si_citta_7c9bac_idx'),
        ),
        migrations.AddIndex(
            model_name='sito',
            index=models.Index(fields=['categoria'], name='heritage_si_categor_2c6555_idx'),
        ),
        migrations.AddConstraint(
            model_name='sito',
            constraint=models.CheckConstraint(condition=models.Q(('latitudine__gte', -90), ('latitudine__lte', 90)), name='sito_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='sito',
            constraint=models.CheckConstraint(condition=models.Q(('longitudine__gte', -180), ('longitudine__lte', 180)), name='sito_lng_range'),
        ),
    ]
