# Generated by Django 5.2.6 on 2025-10-16 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0005_sito_heritage_si_regione_cf873f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilita',
            name='ausili_visivi',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessibilita',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessibilita',
            name='sedia_a_rotelle',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessibilita',
            name='supporto_uditivo',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sito',
            name='accessibilita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siti', to='heritage.accessibilita'),
        ),
        migrations.AlterField(
            model_name='sito',
            name='citta',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sito',
            name='regione',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sito',
            name='unesco_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='accessibilita',
            index=models.Index(fields=['sedia_a_rotelle'], name='heritage_ac_sedia_a_1f5870_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilita',
            index=models.Index(fields=['ausili_visivi'], name='heritage_ac_ausili__c3838d_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilita',
            index=models.Index(fields=['supporto_uditivo'], name='heritage_ac_support_984537_idx'),
        ),
    ]
