# Generated by Django 5.2.6 on 2025-10-16 15:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0006_alter_accessibilita_ausili_visivi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotazioneItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='heritage.itinerario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni_itinerario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'itinerario'], name='heritage_pr_user_id_37c121_idx')],
                'unique_together': {('user', 'itinerario')},
            },
        ),
    ]
