# Generated by Django 5.2.6 on 2025-10-17 09:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0007_prenotazioneitinerario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('data', models.DateField()),
                ('numero_persone', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='heritage.itinerario')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['itinerario'], name='heritage_bo_itinera_ec3abe_idx'), models.Index(fields=['data'], name='heritage_bo_data_6e117a_idx')],
            },
        ),
    ]
